### ISSUE TITLE
Combination Fulma and Fable.Import.Browser conflict

### ISSUE THREAD

**Issue by selketjah** [MangelMaxime/Fulma#142]
Just wanted to inform that there is a conflict with  _Screen_ from Fulma and the one from Fable.Import.Browser

**Show case**
<img width="670" alt="screen shot 2018-05-13 at 18 19 19" src="https://user-images.githubusercontent.com/2250570/39969321-56ce45d4-56da-11e8-85f6-909359e71812.png">

**Intellisense information from error**
val Screen : ScreenType
Full name: Fable.Import.Browser.Screen
Assembly: Fable.Import.Browser

Might be worth mentioning in the documentation.
(in combination with the Color issue, we might want to start a "questions" or "possible issues" page in the documentation)

**Comment by MangelMaxime** [comment]
Ah yes, I didn't see this one coming because I never open `Fable.Import.Browser`.
If you reverse the order to be:

```fs
open Fable.Import.Browser
open Fulma
```

It should fix the intellisense :D (at least for fulma hihi).


I agree on adding a note about this problem on the documentation

**Comment by kunjee17** [comment]
Can't we use universal solution for these kind of problems. And go for `Screen'` for fulma. Just like we did for `box'` ?

**Comment by MangelMaxime** [comment]
To be honest I don't like using `Screen'` because it make it harder to read and type.

IMO user should always write `Browser.xxxx` because this module define a lot of type which overwrite even F# ones. And from my experience we should more or less always use libraries by prefexing then with their name in Fable.

I do it for everything except `React DSL` and `Fulma API`. But some people write the next code for this exact reason:

```
module R =  Fable.Helpers.React

R.div [ ] [ ]
```

You have this kind of conflict existing with others librarie. For example, `Elmish.Browser` conflict with `Fable.Import.Browser` etc.

I used `Box.box'` at the time because this is a reserved keyword in F# synthax. I should probably have renamed it to `Box.div` when I did the rework in the library.

**Comment by selketjah** [comment]
I agree with Maxime that we shouldn't change it do `Screen'`.
But I like the recommendation to always write `Browser.xxx`

So is it ok to add a "recommendation" page in the docs, with this and #134 ?

**Comment by evilz** [comment]
I prefere global open Browser when creating a SPA ;)

Another way to solve the problem is to split in little view/component your code and then open Fulma or Browser in specific module.

When you use Fulma.Column I think you don't need Browser. 
But if so you can:
- inject a function
- order open
- Use full name
