### ISSUE TITLE
Minor change in build.fsx

### ISSUE THREAD

**Issue by kunjee17** [MangelMaxime/Fulma#164]
Hey, @MangelMaxime sorry to post a kind of PR here. But new PC clean up going on so it was easy to set up one line change here. 

Instead of line https://github.com/MangelMaxime/Fulma/blob/master/build.fsx#L108

it will come this. Just to make it working for me in mac
"webpack-dev-server --port free -- --config docs/webpack.config.js"

**Comment by kunjee17** [comment]
@MangelMaxime if you can wait and want me to give PR let me know. I ll do it around weekend.

**Comment by MangelMaxime** [comment]
Sure I can wait the PR.

Also for info, the docs are not working yet with Fable 2 because Fable 2 dropped the support for the plugin system. I need to find another clean way of importing the code strings

Speaking of this part:
<img width="1151" alt="capture d ecran 2018-10-18 a 09 28 20" src="https://user-images.githubusercontent.com/4760796/47137891-30d6d080-d2b8-11e8-9760-cd749603b961.png">

**Comment by kunjee17** [comment]
I came across there. I ll also have a look if I can find out something. I ll give PR soon.
