### ISSUE TITLE
How to change background color ?

### ISSUE THREAD

**Issue by bratfizyk** [MangelMaxime/Fulma#170]
I'm new to Fulma/Bulma and I decided to follow a video tutorial first to develop some understanding of the framework.

I found this one:
https://scrimba.com/p/pV5eHk/cGym4Ta

The HTML around the end of the video looks like this:

```html
        <style>
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
        }
        </style>

	<body>
        <section class="hero is-fullheight has-background-black">
            <div class="hero-body">
                <div class="container">
                    <figure class="image center">
                        <img src="images/bulma-logo-white.png" style="max-width: 512px;">
                    </figure>
                </div>
            </div>
        </section>
	</body>
```

I've found out that the following F# code produces the same HTML:

```fs
        let style = [ Display Display.Flex; JustifyContent TextAlignment.Centered; AlignItems TextAlignment.Centered; MaxWidth "512px" ]

        Hero.hero [ Hero.IsFullHeight; Hero.CustomClass "has-background-black" ] [
            Hero.body [] [
                Container.container [] [
                    Image.image [ ] [
                        img [ Src "./Images/-logo-white.png.png"; Style style ]
                    ]
                ]
            ]
        ]
```

However, the background remains white in my browser, so I'm wondering where did I make a mistake. I've created an app using the SAFE template, but at the moment I focus on the Client part only. The F# code I've just pasted is the only piece of "HTML" I have.

**Comment by kunjee17** [comment]
@bratfizyk I guess it is issue of react style of programming. :) . You have style tag in html page, so that will be implemented to whole html page. But in F# code or even in react code, you are having style object that will not be implemented to whole page.

For Elmish

there are few ways to do that
- Change in main.sass and it will be added as base css to whole application. There also you need to implement for body tag so that got worked accordingly 
- Change in index.html and put style tag there
- Change for specific component and add css class there. Depends on what you like to achieve. 

If you are changing background then first two option may be more viable. 

Let me know if above things make sense and worked for you. You can always find @MangelMaxime and others in gitter channel of Fable or ask for help at fsharp slack web channel.

**Comment by MangelMaxime** [comment]
If you used the SAFE-template to create your project, you will need to upgrade `bulma` dependency [here](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/public/index.html#L9).

As you can see, it's using Bulma `0.6.1` but `background` modifer has been added with version `0.7.0` of Bulma. This is why you get no change.

# Standard way of setting background color of a hero

If you look at [Hero documentation](https://bulma.io/documentation/layout/hero/#colors) you will see that in order to specify the color of a `hero` you need to use the class `is-danger`, `is-black`, etc.

So if you use this code:
```fs
Hero.hero [ Hero.IsFullHeight
            Hero.Color IsBlack]
    [ Hero.body [ ]
        [ Container.container [ ]
            [ Heading.h1 [ ]
                [ str "A big title" ]
              Heading.p [ Heading.IsSubtitle
                          Heading.Is3 ]
                [ str "The subtitle" ] ] ] ]
```

You will get this result:

<img width="1331" alt="capture d ecran 2018-11-20 a 09 26 01" src="https://user-images.githubusercontent.com/4760796/48760476-5172bb80-eca6-11e8-80cc-9fed5608aa38.png">

# Using `has-background-black` is wrong to set the color of a hero section

Using `has-background-black` works too but you will see that the color of the text is also modified which is wrong.

```fs
Hero.hero [ Hero.IsFullHeight
            Hero.CustomClass "has-background-black" ]
    [ Hero.body [ ]
        [ Container.container [ ]
            [ Heading.h1 [ ]
                [ str "A big title" ]
              Heading.p [ Heading.IsSubtitle
                          Heading.Is3 ]
                [ str "The subtitle" ] ] ] ]
```

results in 

<img width="1332" alt="capture d ecran 2018-11-20 a 09 29 58" src="https://user-images.githubusercontent.com/4760796/48760661-dd84e300-eca6-11e8-8b72-e51b71066da5.png">

# Modifiers are also wrapped

If you want to use modifiers, Fulma has them wrapped for you [documentation](https://mangelmaxime.github.io/Fulma/#fulma/modifiers/colors).

So if we take our previous code, we can re-write it like that:

```fs
Hero.hero [ Hero.IsFullHeight
            Hero.Modifiers [ Modifier.BackgroundColor IsBlack ] ]
    [ Hero.body [ ]
        [ Container.container [ ]
            [ Heading.h1 [ ]
                [ str "A big title" ]
              Heading.p [ Heading.IsSubtitle
                          Heading.Is3 ]
                [ str "The subtitle" ] ] ] ]
```

**Comment by bratfizyk** [comment]
Excellent - thanks for a detailed answer. That's exactly what I needed.
Also, I'll remember for future to ask such questions via gitter.
