### ISSUE TITLE
Idea for Fulma examples

### ISSUE THREAD

**Issue by rmunn** [MangelMaxime/Fulma#48]
Here's an idea for a larger demo to show off how to use Fulma and Elmish together, and how to hook up updates to buttons, etc.:

A fictional code-discussion site called Tail Recursion. (Tagline: "Because with tail recursion, you'll rarely see a stack overflow.") The sample shows three questions: "Is this code tail-recursive?", "Why is tail recursion important?" and "What is the average wingspeed of an unladen swallow?" There are a couple of sample answers and comments (e.g., the last question has a comment asking which continent the swallow is from), and you can vote up or down on the answers. The answers use the [media object](https://mangelmaxime.github.io/Fable.Elmish.Bulma/#components/media) for their layout, with a couple of sample avatars and user accounts (I'd be willing to have my avatar, username, and real name used in the examples if you want, and another account could have the Fulma logo for its avatar). There's also a "Post your answer" textarea & button, with another demo account already "logged in". (The demo would not *actually* be doing any account management, it would just show an avatar and the name "Demo User" next to whatever gets typed in the box. There would also be no storage -- the demo would reset anytime the user hit Ctrl+R.)

Also, in addition to adding answers, users can vote answers up and down. To show off how everything in Fable.Elmish is interconnected through the model, voting answers up and down won't just show a numeric score next to the answer the way Stack Overflow does. It will also display a row of thumb-up or thumb-down icons underneath the answer, one icon for each point the answer has. (Since this is a demo, there is no restriction on users voting multiple times, but scores on answers are capped between -5 and +5 points: trying to downvote a -5 answer, or upvote a +5 answer, pops up a little error saying "You've already upvoted / downvoted this answer 5 times, isn't that enough?" and the further clicks are not registered. That error goes away if you downvoted from +5 down to +4, or upvote from -5 up to -4.) The thumb-up icons appear in green, and the thumb-down icons appear in red. Furthermore, the score is also tied to the background color of the answer: going from 0 to +5 shades it from white to a pale green (at +5, the green color is pronounced, but still pale enough that black text on it is still readable), and going from 0 to -5 shades the background color from white to a pale red. All of these things — the numeric score next to the answer, the number of thumbs-up or thumbs-down icons, and the background color of the answer — are simply tied to the model, and the +1 and -1 buttons just send Answer.Upvote and Answer.Downvote messages, and the model update code simply adds 1 or subtracts 1 (and caps at 5, sending a Cmd.PopupMsg command if necessary). The demo emphasizes that nothing in the button code needs to know about the background-color, or the row of thumb-up icons — everything is tied together through the model, and that's all you need to do to make it all work. No special Javascript needed at all!

The result should be something that *looks* pretty sophisticated, but whose code is remarkably clear and easy to understand. Which is the whole point of Fulma: how clean and neat it makes your site's code.

If my textual description is clear, great! If there's something unclear about the above, let me know and I'll see if I can sketch out a mockup in https://www.draw.io/ or something.

**Comment by MangelMaxime** [comment]
Thanks for the complete sample. I think the text description is enough. 

I am already working on a demo for DotnetConf and FableConf which will have some of this features. I made it a bit more complete/complex because I am demonstrating how to support login, session, fetching resource etc. So yes it's too much complex for new people I think we will be able to take some part and made an independent sample looking like yours.

In fact, my current "demo" is more a real world sample of an "isomorphic application with Fable" (Express + Elmish) than just showing how clean Fulma can be. But I think both demo can work together by saying now that you understand how to use Fulma and how clean it can be here is a full web application (server + client) to guide you on the next step. Or vice versa.

I hope, I am clear enough in my explanations...

**Comment by MangelMaxime** [comment]
@rmunn Just to inform you. So I am using your github avatar and your name in the application (will be used for FableConf and be hosted on github).

If you don't want any more, and I will make a virtual person. Just find it better to be real person :D

**Comment by MangelMaxime** [comment]
I am starting doing work on this sample.

**Comment by MangelMaxime** [comment]
Hello @rmunn , I finally have a first version of the [fulma-demo online](https://github.com/MangelMaxime/fulma-demo/blob/master/src/App.fs#L16-L65).

Most of the feature you requested are here except:

- green/red nuance on the answers background. I tried it but the look and feel didn't feel right
- All the website, finally use a persistent storage, I needed to do that in order to keep the code in `State.fs` clean enough. This also allow me to demonstrate how to use a drop-down in the application so it's probably a good compromise :)

Also, please note the website should be responsive too. We can probably improve it especially, on the answer part.
