### ISSUE TITLE
Date picker z position is wrong on iPad

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#56]
![img_2142](https://user-images.githubusercontent.com/873919/30846743-7ec434d8-a2a1-11e7-8971-a0dfbb3cc783.PNG)

**Comment by alfonsogarciacaro** [comment]
Can reproduce both on Chrome and Safari on iPad. Works fine on Safari on macOS.

**Comment by MangelMaxime** [comment]
I believe using z-index should fix the problem. And as i added the calendar style to [`Config`](https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma.Elmish/DatePicker/Types.fs#L33) user will also be able to center the calendar if their want etc.

Will publish a fix later

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @vasily-kirichenko Can you please check that I fixed the solution ? I don't have an iPad and the simulator wasn't reproducing the bug.

**Comment by alfonsogarciacaro** [comment]
Yeah, it's working for me both on Chrome and Safari on iPad :clap: :clap:

**Comment by vasily-kirichenko** [comment]
it’s fixed, but I found another bug - the calendar does not pops up once a date selected:

https://drive.google.com/open?id=0B8HLQUKik9VtTHJid25lcmNSakE

**Comment by MangelMaxime** [comment]
@vasily-kirichenko Ok I know the source of the bug.

If you click outside of the input and re-select it. Then it will work. I will include the same fix, I made for the mouse.

**Comment by MangelMaxime** [comment]
@vasily-kirichenko If you select a date. Then click outside the input to loose the focus and then inside the input is it working ?

**Comment by alfonsogarciacaro** [comment]
I'm having the same problem (also both on Chrome and Safari on iPad). Touching outside and then the date picker again doesn't work. I thought it may be something related with the touch events, but I don't have the problem when using my Android phone.

**Comment by alfonsogarciacaro** [comment]
BTW, on iPad when you touch outside, the input box doesn't get deselected. This is probably the problem. Apparently this is the behaviour of input boxes (in any web) in the iPad 😕

**Comment by MangelMaxime** [comment]
This is really strange because, we had the same problem before even on "desktop browsers" but I fixed it by listening to `OnFocus` and `OnClick` event. In reality, I probably could listen only for `OnClick`.

Listeners registrations: https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma.Elmish/DatePicker/View.fs#L106-L107
Do not worry, the event is dispatch only once even if we have two listeners thanks to this lines: https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma.Elmish/DatePicker/View.fs#L22

And according to my quick search, `OnClick` should work the same for touchscreen applications. Here, I believe this is something special about iPad as you seems to describe @alfonsogarciacaro 

I will not be able to fix it myself, because I don't have the device... :confused:
