### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#58]
https://github.com/MangelMaxime/Fulma/blob/2dcc27fad84aaae8fa9e5efd84acf3b6e221a2d6/docs/src/Fulma/Components/Media/State.fs

contains `Field.field` and `Control.control_div`, however they do not exist anymore. 

How the documentation been generated?..

**Comment by MangelMaxime** [comment]
If by documentation you mean the big string in the file then it's a manual copy paste from the [view code](https://github.com/MangelMaxime/Fulma/blob/master/docs/src/Fulma/Components/Media/View.fs#L14-L31)

When change `Forms` api I fixed the view code because the compiler was complaining but I forget to update the "displayed code".
