### ISSUE TITLE
Size improvements

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#62]
This issue will tracks our trial to reduce the bundle size of an Elmish + Fulma application.

We will use [fulma-demo](https://github.com/MangelMaxime/fulma-demo) as a reference when the demo site is ready. This website should include the same dependencies than a classic Elmish application:

- Elmish
- Fable.Powerpack
- Fulma
- Fulma.Extensions
- Fulma.Elmish
- etc.

**Comment by alfonsogarciacaro** [comment]
Sorry, I didn't have time to keep on working on #50, but that PR helps reduce the bundle size, we just need to extend the optimizations to other files (inlining, using enums instead of DUs where possible...)

**Comment by MangelMaxime** [comment]
No problem, you show me the way. So I will be able to continue it. 

I am still wondering why inlining is helping.  Because if we use the function a lot then we will increase the bundle size as we copy the same code everywhere no?

**Comment by alfonsogarciacaro** [comment]
You're right, that's why you need to be careful when inlining :) This is better done for small helpers that mainly provide syntax sugar (there are many of them in Fulma). If you inline the code you save a function call and also you don't have to import another file, and if there are no references, the file won't be put into the bundle.

> Please note that tree shaking can optimize code that is not referenced in the root module **but not in nested modules** (and files like `Column.fs` have many nested modules).

Also in some occasions Fable can optimize inline code [as in this example](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0A%0Atype%20Test%20%3D%0A%20%20%7C%20Foo%0A%20%20%7C%20Bar%20of%20string%0A%0Alet%20helper1%20(opts%3A%20Test%20list)%20%3D%20keyValueList%20CaseRules.LowerFirst%20opts%0Alet%20inline%20helper2%20(opts%3A%20Test%20list)%20%3D%20keyValueList%20CaseRules.LowerFirst%20opts%0A%0Alet%20x%20%3D%20helper1%20%5BFoo%3B%20Bar%20%22jaja%22%5D%0Alet%20y%20%3D%20helper2%20%5BFoo%3B%20Bar%20%22jaja%22%5D%0A%0A&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2) where `keyValueList` can be optimized into a literal JS object, so you don't need to import the actual type declaration.

**Comment by MangelMaxime** [comment]
Hum. Ok I see.

Will work on it when the sample is ready to have a comparison reference. If you have any others idea don't hesitate to share :)

**Comment by kunjee17** [comment]
Inline functions almost crashed Fable.Chessie. So, better be careful. 

@MangelMaxime As I shared with you I am using Fulma with other extension in big fat business application. So, whatever optimisation can be done, will surely show big effect there because of the size.  

So, all that details are available and I am very much happy to help.

**Comment by MangelMaxime** [comment]
@kunjee17 Yes I saw that for Fable.Chessie but Fulma helpers are not got to be "bind", "compose" like we do in Fable.Chessie. So you should be fine.

**Comment by MangelMaxime** [comment]
Closing in favor of #92
