### ISSUE TITLE
Too many modules with same name

### ISSUE THREAD

**Issue by evilz** [MangelMaxime/Fulma#72]
Fulma should make dev easier ...

sometime it does not.

![pasted image at 2017_10_16 03_33 pm](https://user-images.githubusercontent.com/2937862/31615863-49bcf6d6-b28b-11e7-86bf-3da9f844bf29.png)

we need to make a pass on naming things ?

**Comment by MangelMaxime** [comment]
You got a lot of results but some are wrong I think because the suggestion isn't case sensitive. For example, in [panel.fs](https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma/Components/Panel.fs#L98) we only have `heading` in lowercase not in capital case.

I am open to idea, but because the names are coming from Bulma implementation, not much we can do here. In general,

**Comment by evilz** [comment]
Oki, got no nice idea ... I close this
