### ISSUE TITLE
Update Bulma to 0.6.x

### ISSUE THREAD

**Issue by kunjee17** [MangelMaxime/Fulma#91]
Bulma is moving fast in current version and have quite a few changes. We should be moving towards it.

Do we have any road map for upgrades ?

**Comment by MangelMaxime** [comment]
Yes supported 0.6.x is planned and to be honest between 0.5.2 and 0.6.1 (latest version today) their isn't that much new features most of them are usable in current version of Fulma. And yes perhaps you need a `div + ClassName` sometimes :)

I want to take time to improve the user experience in Fulma first and them update to latest of Bulma. This will avoid to develop twice the same feature :) I promise this update for a long time now, but I was having some deadlines to follow at work and started other project/lib needed for my job.

So I have considered Fulma usable in current state and relay it back since september/october. 😞 But hopefully, I should have time again this end or year or at the beginning of January :) At lest it's my goal, to release the better user experience + support for latest version of Bulma in January.

**Comment by MangelMaxime** [comment]
Note: #93 is still missing support for `fixed navbar`

**Comment by kunjee17** [comment]
@MangelMaxime got that. I tried updated Bulma few days back. Navbar is broken. Didn't found any other issue though

**Comment by MangelMaxime** [comment]
Yes Bulma replace the `nav` with `navbar`. I already made the port on the next version. Just forget to add suport for "fixed navbar". :D
